version: '3'
services:
  app:
    container_name: node-cinema-db
    restart: always
    env_file: .env
    build: .
    ports:
      - '80:3000'
    links:
      - mongo
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
