version: '3'
services:
  app:
    image: isuru117/cinema-db-backend
    restart: always
    env_file: .env
    ports:
      - '80:3000'
    links:
      - mongo
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
