version: '3'
services:
  app:
    image: isuru117/cinema-db-backend:${TAG_VERSION}
    restart: always
    environment: 
      - MONGO_DB_URI=${MONGO_DB_URI}
      - PORT=${APP_PORT}
    ports:
      - '80:3000'
    links:
      - mongo
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo:5.0.2
    volumes:
      - './data:/data/db'
