version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: login to docker
          command: |
            echo "${DOCKER_PASS}" | docker login --username ${DOCKER_USER} --password-stdin
      - run:
          name: build docker image
          command: docker build -t ${IMAGE_NAME} .
      - run:
          name: push to docker hub
          command: docker push ${IMAGE_NAME}
workflows:
  version: 2
  build-workflow:
    jobs:
      - build