version: 2.1

defaults: &defaults
  working_directory: ~/repo

orbs:
  aws-cli: circleci/aws-cli@2.0.3

commands:
  docker-build:
    steps:
      - checkout
      - run:
          name: build docker image
          command: docker build -t ${IMAGE_NAME} .
jobs:
  build:
    <<: *defaults
    machine: true
    steps:
      - docker-build
  deploy:
    <<: *defaults
    machine: true
    steps:
      - docker-build
      - run:
          name: login to docker
          command: echo "${DOCKER_PASS}" | docker login --username ${DOCKER_USER} --password-stdin
      - run:
          name: push to docker hub
          command: docker push ${IMAGE_NAME}
      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-region: AWS_DEFAULT_REGION
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
      - run:
          name: copy docker-compose.yml to ec2 instance
          command: |
            scp ~/repo/docker-compose.yml ${EC2_USERNAME}@${EC2_PUBLIC_DNS}:${EC2_DEPLOY_PATH}
      - run:
          name: ssh and run docker-compose
          command: |
            ssh -o StrictHostKeyChecking=no ${EC2_USERNAME}@${EC2_PUBLIC_DNS} \
            MONGO_DB_URI=${MONGO_DB_URI} APP_PORT=${APP_PORT} sudo -E docker-compose up --detach
workflows:
  build-push-flow:
    jobs:
      - build:
          filters:
            branches:
              ignore: main
      - deploy:
          filters:
            branches:
              only: main